project:
  type: website

website:
  title: "R Series - statml.in"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/yuvrajiro
      - icon: twitter
        href: https://twitter.com/distribution_fu
format:
  html:
    theme: simplex
    css: styles.css



